Models/Rentadevolucion.cs
using System;
using System.Collections.Generic;

namespace CrudAudiovisuales.models;

public partial class Rentadevolucion
{
    public int NoPrestamo { get; set; }

    public int EmpleadoId { get; set; }

    public int EquipoId { get; set; }

    public int UsuarioId { get; set; }

    public DateTime FechaPrestamo { get; set; }

    public DateTime? FechaDevolucion { get; set; }

    public string? Comentario { get; set; }

    public string? Estado { get; set; }

    public virtual Empleado Empleado { get; set; } = null!;

    public virtual Equipo Equipo { get; set; } = null!;

    public virtual Usuario Usuario { get; set; } = null!;
}

Controllers/RentadevolucionsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CrudAudiovisuales.models;
using Microsoft.AspNetCore.Authorization;
using CrudAudiovisuales.models.DTO;
using ClosedXML.Excel;
using System.Data;
using OfficeOpenXml;

namespace CrudAudiovisuales.Controllers
{
    public class RentadevolucionsController : Controller
    {
        private readonly AudiovisualesContext _context;

        public RentadevolucionsController(AudiovisualesContext context)
        {
            _context = context;
        }

        // GET: Rentadevolucions
        public async Task<IActionResult> Index()
        {
            var audiovisualesContext = _context.Rentadevolucions.Include(r => r.Empleado).Include(r => r.Equipo).Include(r => r.Usuario);
            return View(await audiovisualesContext.ToListAsync());
        }

        // GET: Rentadevolucions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Rentadevolucions == null)
            {
                return NotFound();
            }

            var rentadevolucion = await _context.Rentadevolucions
                .Include(r => r.Empleado)
                .Include(r => r.Equipo)
                .Include(r => r.Usuario)
                .FirstOrDefaultAsync(m => m.NoPrestamo == id);
            if (rentadevolucion == null)
            {
                return NotFound();
            }

            return View(rentadevolucion);
        }

       // GET: Rentadevolucions/Create
        public IActionResult Create()
        {
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id");
            ViewData["EquipoId"] = new SelectList(_context.Equipos, "Id", "Id");
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id");
            return View();
        }

        // POST: Rentadevolucions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("NoPrestamo,EmpleadoId,EquipoId,UsuarioId,FechaPrestamo,FechaDevolucion,Comentario,Estado")] RentadevolucionDto rentadevolucionDto)
        {
            if (ModelState.IsValid)
            {
                var rentadevolucion = new Rentadevolucion
                {
                    NoPrestamo = rentadevolucionDto.NoPrestamo,
                    EmpleadoId = rentadevolucionDto.EmpleadoId,
                    EquipoId = rentadevolucionDto.EquipoId,
                    UsuarioId = rentadevolucionDto.UsuarioId,
                    FechaPrestamo = rentadevolucionDto.FechaPrestamo,
                    FechaDevolucion = rentadevolucionDto.FechaDevolucion,
                    Comentario = rentadevolucionDto.Comentario,
                    Estado = rentadevolucionDto.Estado
                };

                _context.Add(rentadevolucion);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", rentadevolucionDto.EmpleadoId);
            ViewData["EquipoId"] = new SelectList(_context.Equipos, "Id", "Id", rentadevolucionDto.EquipoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", rentadevolucionDto.UsuarioId);
            return View(rentadevolucionDto);
        }

        // GET: Rentadevolucions/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Rentadevolucions == null)
            {
                return NotFound();
            }

            var rentadevolucion = await _context.Rentadevolucions.FindAsync(id);
            if (rentadevolucion == null)
            {
                return NotFound();
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", rentadevolucion.EmpleadoId);
            ViewData["EquipoId"] = new SelectList(_context.Equipos, "Id", "Id", rentadevolucion.EquipoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", rentadevolucion.UsuarioId);
            return View(rentadevolucion);
        }

        // POST: Rentadevolucions/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("NoPrestamo,EmpleadoId,EquipoId,UsuarioId,FechaPrestamo,FechaDevolucion,Comentario,Estado")] Rentadevolucion rentadevolucion)
        {
            if (id != rentadevolucion.NoPrestamo)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rentadevolucion);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentadevolucionExists(rentadevolucion.NoPrestamo))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["EmpleadoId"] = new SelectList(_context.Empleados, "Id", "Id", rentadevolucion.EmpleadoId);
            ViewData["EquipoId"] = new SelectList(_context.Equipos, "Id", "Id", rentadevolucion.EquipoId);
            ViewData["UsuarioId"] = new SelectList(_context.Usuarios, "Id", "Id", rentadevolucion.UsuarioId);
            return View(rentadevolucion);
        }

        // GET: Rentadevolucions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Rentadevolucions == null)
            {
                return NotFound();
            }

            var rentadevolucion = await _context.Rentadevolucions
                .Include(r => r.Empleado)
                .Include(r => r.Equipo)
                .Include(r => r.Usuario)
                .FirstOrDefaultAsync(m => m.NoPrestamo == id);
            if (rentadevolucion == null)
            {
                return NotFound();
            }

            return View(rentadevolucion);
        }

        // POST: Rentadevolucions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Rentadevolucions == null)
            {
                return Problem("Entity set 'AudiovisualesContext.Rentadevolucions'  is null.");
            }
            var rentadevolucion = await _context.Rentadevolucions.FindAsync(id);
            if (rentadevolucion != null)
            {
                _context.Rentadevolucions.Remove(rentadevolucion);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<ActionResult> ExportToExcelAsync()
    {
        // Get your list of models
        List<Rentadevolucion> models = _context.Rentadevolucions.Include(r => r.Empleado).Include(r => r.Equipo).Include(r => r.Usuario).ToList();

        // Create a new Excel package
        ExcelPackage package = new ExcelPackage();
        ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

        // Add a new worksheet to the Excel package
        ExcelWorksheet worksheet = package.Workbook.Worksheets.Add("Sheet1");

                // Set the column names in the first row
        worksheet.Cells[1, 1].Value = "NoPrestamo";
        worksheet.Cells[1, 2].Value = "EmpleadoId";
        worksheet.Cells[1, 3].Value = "EquipoId";
        worksheet.Cells[1, 4].Value = "UsuarioId";
        worksheet.Cells[1, 5].Value = "FechaPrestamo";
        worksheet.Cells[1, 6].Value = "FechaDevolucion";
        worksheet.Cells[1, 7].Value = "Comentario";
        worksheet.Cells[1, 8].Value = "Estado";

        // Populate the Excel sheet with data
        int row = 2; // Start from the second row (first row is for headers)
        foreach (var model in models)
        {
            worksheet.Cells[row, 1].Value = model.NoPrestamo;
            worksheet.Cells[row, 2].Value = model.EmpleadoId;
            worksheet.Cells[row, 3].Value = model.EquipoId;
            worksheet.Cells[row, 4].Value = model.UsuarioId;
            worksheet.Cells[row, 5].Value = model.FechaPrestamo;
            worksheet.Cells[row, 6].Value = model.FechaDevolucion;
            worksheet.Cells[row, 7].Value = model.Comentario;
            worksheet.Cells[row, 8].Value = model.Estado;

            row++;
        }

        // Generate a unique filename for the Excel file
        string fileName = "Export_" + DateTime.Now.ToString("yyyyMMddHHmmss") + ".xlsx";

        // Set the content type and headers
        Response.ContentType = "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";
        Response.Headers.Append("content-disposition", "attachment;  filename=" + fileName);

        // Write the Excel package to the response stream
        await Response.Body.WriteAsync(package.GetAsByteArray());

        return new EmptyResult();
    }
        private bool RentadevolucionExists(int id)
        {
          return (_context.Rentadevolucions?.Any(e => e.NoPrestamo == id)).GetValueOrDefault();
        }
    }
}

Views/Rentadevolucions/Create.cshtml
@model CrudAudiovisuales.models.Rentadevolucion

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Rentadevolucion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class ="form-control" asp-items="ViewBag.EmpleadoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="EquipoId" class="control-label"></label>
                <select asp-for="EquipoId" class ="form-control" asp-items="ViewBag.EquipoId"></select>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class ="form-control" asp-items="ViewBag.UsuarioId"></select>
            </div>
            <div class="form-group">
                <label asp-for="FechaPrestamo" class="control-label"></label>
                <input asp-for="FechaPrestamo" class="form-control" />
                <span asp-validation-for="FechaPrestamo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDevolucion" class="control-label"></label>
                <input asp-for="FechaDevolucion" class="form-control" />
                <span asp-validation-for="FechaDevolucion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Rentadevolucions/Delete.cshtml
@model CrudAudiovisuales.models.Rentadevolucion

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Rentadevolucion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPrestamo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPrestamo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDevolucion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDevolucion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="NoPrestamo" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Rentadevolucions/Details.cshtml
@model CrudAudiovisuales.models.Rentadevolucion

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Rentadevolucion</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaPrestamo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaPrestamo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaDevolucion)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaDevolucion)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Comentario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Comentario)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Estado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Estado)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Empleado)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Empleado.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Equipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Equipo.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Usuario)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Usuario.Id)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.NoPrestamo">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Rentadevolucions/Edit.cshtml
@model CrudAudiovisuales.models.Rentadevolucion

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Rentadevolucion</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="NoPrestamo" />
            <div class="form-group">
                <label asp-for="EmpleadoId" class="control-label"></label>
                <select asp-for="EmpleadoId" class="form-control" asp-items="ViewBag.EmpleadoId"></select>
                <span asp-validation-for="EmpleadoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EquipoId" class="control-label"></label>
                <select asp-for="EquipoId" class="form-control" asp-items="ViewBag.EquipoId"></select>
                <span asp-validation-for="EquipoId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="UsuarioId" class="control-label"></label>
                <select asp-for="UsuarioId" class="form-control" asp-items="ViewBag.UsuarioId"></select>
                <span asp-validation-for="UsuarioId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaPrestamo" class="control-label"></label>
                <input asp-for="FechaPrestamo" class="form-control" />
                <span asp-validation-for="FechaPrestamo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaDevolucion" class="control-label"></label>
                <input asp-for="FechaDevolucion" class="form-control" />
                <span asp-validation-for="FechaDevolucion" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Comentario" class="control-label"></label>
                <input asp-for="Comentario" class="form-control" />
                <span asp-validation-for="Comentario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Estado" class="control-label"></label>
                <input asp-for="Estado" class="form-control" />
                <span asp-validation-for="Estado" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Views/Rentadevolucions/Index.cshtml
@model IEnumerable<CrudAudiovisuales.models.Rentadevolucion>

@{
    ViewData["Title"] = "Renta y devolucion";
}

<h1>Renta y devolucion</h1>

<p>
    <a asp-action="Create" class="btn btn-danger">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FechaPrestamo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaDevolucion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Comentario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Estado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Empleado)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Equipo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Usuario)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.FechaPrestamo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaDevolucion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Comentario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Estado)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Empleado.Nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Equipo.Descripcion)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Usuario.Nombre)
            </td>
            <td>
                    <a asp-action="Edit" asp-route-id="@item.NoPrestamo" class="btn btn-danger">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.NoPrestamo" class="btn btn-light">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.NoPrestamo" class="btn btn-warning">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>
    @using (Html.BeginForm("ExportToExcel", "Rentadevolucions", FormMethod.Post))
{
    <button type="submit">Export to Excel</button>
}